data:
    batch_size: 16
    workers: 4
arch:
    num_classes: 2
    model: resnet152
    pretrained: true
optimizer:
    type: sgd
    lr: 0.0001
    lr_decay_epochs: [4]
    momentum: 0.9
    weight_decay: 0.0001
training:
    logs_dir: logs
    checkpoints_dir: checkpoints
    experiment_name: resnet152
    print_freq: 20
    checkpoint_epochs: 1
    log_dir:
    epochs: 100
    debug: false
    early_stopping_mindelta: 0
    early_stopping_patience: 15
    resume:
